### ISSUE TITLE
疑惑

### ISSUE THREAD

**Issue by hongfishing** [sst4rb0y/SDP_Dynamic_Authorization_access_System_based_on_zero_trust#1]
您好，最近在学习SDP，但毫无头绪，看到您的项目尝试复现，但是始终通信失败，也可能是我数据库连接的方式不对，可不可以请您指点一下数据库的连接方式

**Comment by sst4rb0y** [comment]
哥，我这个不知道算不算SDP，另外配置数据库在authSrc下配置下config.yaml就行了

**Comment by hongfishing** [comment]
> 

可不可以加您一个联系方式请您帮忙看一下，有偿，想用您的这段代码活过中检

**Comment by sst4rb0y** [comment]
最近有点忙，可以先邮件联系我加微信，话说这点代码能做啥

**Comment by hongfishing** [comment]
哥你微信号是多少，我只想活过中检，代码量挺多的
&nbsp;


一条鲤鱼
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月16日(星期四) 下午4:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sst4rb0y/SDP_Dynamic_Authorization_access_System_based_on_zero_trust] 疑惑 (Issue #1)





 
最近有点忙，可以先邮件联系我加微信，话说这点代码能做啥

**Comment by sst4rb0y** [comment]
_YLCao
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年3月16日 16:08
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [sst4rb0y/SDP_Dynamic_Authorization_access_System_based_on_zero_trust] 疑惑 (Issue #1)
        
      
    
  

哥你微信号是多少，我只想活过中检，代码量挺多的

&nbsp;





一条鲤鱼

***@***.***







&nbsp;









------------------&nbsp;原始邮件&nbsp;------------------

发件人: ***@***.***&gt;; 

发送时间: 2023年3月16日(星期四) 下午4:04

收件人: ***@***.***&gt;; 

抄送: ***@***.***&gt;; ***@***.***&gt;; 

主题: Re: [sst4rb0y/SDP_Dynamic_Authorization_access_System_based_on_zero_trust] 疑惑 (Issue #1)











 

最近有点忙，可以先邮件联系我加微信，话说这点代码能做啥

**Comment by vlglg** [comment]
哥，可以加个微信吗，想咨询下这个项目的具体内容

**Comment by sst4rb0y** [comment]
close
