### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by chasterchan** [sst4rb0y/SDP_Dynamic_Authorization_access_System_based_on_zero_trust#2]
我在运行代码的时候显示·连接数据库失败，请问提供的文件是不是缺少了数据库文件

**Comment by sst4rb0y** [comment]
你得启动一个数据库，具体看代码。另外，这项目就是个demo，没啥参考价值，后续我会将此归档。

**Comment by chasterchan** [comment]
您的数据库数据都是写在了d.py文件里面吗，还是说这个数据库得自己创建写入数据，谢谢。

**Comment by sst4rb0y** [comment]
答案是后者。请阅读src/main/AuthSrv/AuthServer.py第60行的代码。另外test文件夹下的内容没有意义。

**Comment by chasterchan** [comment]
期待您的最终归档，谢谢解答～
